name: Deploy to FTP

on:
  push:
    branches:
      - main  # ветка, при пуше в которую будет выполняться деплой

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        ftp-server: ftp://your-ftp-server.com
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./  # директория с вашим сайтом
        git-ftp-args: --insecure
