name: Deploy to 000webhost

on:
  push:
    branches:
      - main  # Ветка, при пуше в которую будет выполняться деплой

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: files.000webhost.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./public_html  # Директория с вашим сайтом
        git-ftp-args: --insecure
